apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ADService
  description: Test service for backstage
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: AD Team
